language: node_js
node_js:
# Can't run on node 12 yet, see https://github.com/cryptocoinjs/secp256k1-node/issues/142
#  - "node"
  - "lts/*"
# Report coverage
after_success:
  - "npm i codecov"
  - "node_modules/.bin/codecov"
